# Generated by Django 4.1.3 on 2022-11-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leagues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "leagues",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Seasons",
            fields=[
                ("year", models.IntegerField(primary_key=True, serialize=False)),
                ("number_of_games", models.IntegerField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.leagues",
                    ),
                ),
            ],
            options={
                "db_table": "seasons",
                "managed": True,
                "unique_together": {("year", "league")},
            },
        ),
        migrations.CreateModel(
            name="Sports",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "sports",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.leagues",
                    ),
                ),
            ],
            options={
                "db_table": "teams",
                "managed": True,
                "unique_together": {("name", "league")},
            },
        ),
        migrations.CreateModel(
            name="AwayTeams",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="sportleagues.teams",
                    ),
                ),
            ],
            options={
                "db_table": "away_teams",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="GameDays",
            fields=[
                (
                    "seasons_year",
                    models.OneToOneField(
                        db_column="seasons_year",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="sportleagues.seasons",
                    ),
                ),
                ("league_id", models.IntegerField()),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "game_days",
                "managed": True,
                "unique_together": {("seasons_year", "date", "league_id")},
            },
        ),
        migrations.CreateModel(
            name="HomeTeams",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="sportleagues.teams",
                    ),
                ),
            ],
            options={
                "db_table": "home_teams",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jersey_number", models.IntegerField()),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.teams",
                    ),
                ),
            ],
            options={
                "db_table": "players",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="leagues",
            name="sport",
            field=models.ForeignKey(
                db_column="sport",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="sportleagues.sports",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leagues",
            unique_together={("sport", "name")},
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("league_id", models.IntegerField()),
                ("home_team_score", models.IntegerField()),
                ("away_team_score", models.IntegerField()),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.awayteams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.hometeams",
                    ),
                ),
                (
                    "season_year",
                    models.ForeignKey(
                        db_column="season_year",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.gamedays",
                    ),
                ),
            ],
            options={
                "db_table": "games",
                "managed": True,
                "unique_together": {
                    ("season_year", "league_id", "date", "home_team", "away_team")
                },
            },
        ),
        migrations.CreateModel(
            name="TeamRecords",
            fields=[
                (
                    "season_year",
                    models.OneToOneField(
                        db_column="season_year",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="sportleagues.seasons",
                    ),
                ),
                ("league_id", models.IntegerField()),
                ("win", models.IntegerField()),
                ("loss", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.teams",
                    ),
                ),
            ],
            options={
                "db_table": "team_records",
                "managed": True,
                "unique_together": {("season_year", "league_id", "team")},
            },
        ),
        migrations.CreateModel(
            name="PlayerStatistics",
            fields=[
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="sportleagues.players",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sportleagues.games",
                    ),
                ),
            ],
            options={
                "db_table": "player_statistics",
                "managed": True,
                "unique_together": {("player", "game")},
            },
        ),
    ]
